version: '3.8'

services:
  robot:
    build: .
    container_name: rpi-server-container
    # host mode is essential for WebRTC/UDP low latency
    network_mode: "host"
    # privileged gives access to /dev/video* and /dev/gpiochip*
    privileged: true
    restart: always
    shm_size: '512mb'
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - PYTHONUNBUFFERED=1