version: '3.8'

services:
  rpi-server:
    
    image: ghcr.io/yoloprojekat/rpi-server:latest
    container_name: pametno_vozilo_server
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"